
model:
  arch: vicuna7b
  load_finetuned: True 
  load_pretrained: False

  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth"
  finetuned: 'model_weights/bliva_vicuna7b.pth'

  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16" 
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "model_weights/vicuna-7b-v0"

  # generation configs
  prompt: ""


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 224
        eval:
          name: "blip_image_eval"
          image_size: 224 
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"
